# Generated by Django 4.0.6 on 2022-08-10 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bath', models.BooleanField(default=False)),
                ('clipping', models.CharField(choices=[('SEM_SERVICO', 'Sem Serviço'), ('TOSA_TESOURA', 'Tosa na Tesoura'), ('TOSA_MAQUINA', 'Tosa na Máquina'), ('TOSA_BEBE', 'Tosa Bebê'), ('TOSA_RACA', 'Tosa de Raça'), ('TOSA_VERAO', 'Tosa Verão'), ('TOSA_HIGIENICA', 'Tosa Higiênica'), ('TOSA_ESTETICA', 'Tosa Estética')], max_length=15)),
                ('hydration', models.BooleanField(default=False)),
                ('clearance', models.BooleanField(default=False)),
                ('brush_teeth', models.BooleanField(default=False)),
                ('cut_nails', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('date_appointment', models.DateField()),
                ('hour_appointment', models.TimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmodel')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.petmodel')),
            ],
            options={
                'verbose_name': 'scheduling',
                'verbose_name_plural': 'schedules',
                'db_table': 'SCHEDULING',
            },
        ),
    ]
