# Generated by Django 4.0.6 on 2022-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customermodel_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='birth_date',
            field=models.DateField(blank=True, db_column='BIRTH_DATE', null=True),
        ),
    ]
