# Generated by Django 4.0.6 on 2022-08-08 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_column='EXTERNAL_ID', default=uuid.uuid4, editable=False, unique=True)),
                ('value_money', models.FloatField(db_column='VALUE_MONEY')),
                ('amount_paid', models.FloatField(db_column='AMOUNT_PAID')),
                ('payment_type', models.CharField(choices=[('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência bancária')], db_column='TYPE_CLIPPING', max_length=14)),
                ('registration_date', models.DateTimeField(db_column='REGISTRATION_DATE')),
                ('pay_day', models.DateField(db_column='PAY_DAY')),
                ('is_paid', models.BooleanField(db_column='IS_PAID', default=False)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'PAYMENT',
            },
        ),
    ]
