# Generated by Django 4.0.6 on 2022-08-08 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_column='EXTERNAL_ID', default=uuid.uuid4, editable=False, unique=True)),
                ('date_initial', models.DateField(db_column='DATE_INITIAL')),
                ('date_final', models.DateField(db_column='DATE_FINAL')),
                ('scheduling_amount', models.PositiveIntegerField(db_column='SCHEDULING_AMOUNT')),
                ('animal', models.ForeignKey(db_column='ANIMAL', on_delete=django.db.models.deletion.CASCADE, to='animal.animalmodel')),
                ('payment', models.ForeignKey(db_column='PAYMENT', on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmodel')),
            ],
            options={
                'verbose_name': 'monthly',
                'verbose_name_plural': 'monthlies',
                'db_table': 'MONTHLY',
            },
        ),
    ]
