# Generated by Django 4.0.6 on 2022-08-10 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_initial', models.DateField()),
                ('date_final', models.DateField()),
                ('scheduling_amount', models.PositiveIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmodel')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.petmodel')),
            ],
            options={
                'verbose_name': 'monthly',
                'verbose_name_plural': 'monthlies',
                'db_table': 'MONTHLY',
            },
        ),
    ]
