# Generated by Django 4.0.6 on 2022-08-02 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customermodel_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('breed', models.CharField(choices=[('Akita', 'Akita'), ('American Bully', 'American Bully'), ('American staffordshire terrier', 'American staffordshire terrier'), ('Basenji', 'Basenji'), ('Basset hound', 'Basset hound'), ('Beagle', 'Beagle'), ('Bernese', 'Bernese'), ('Bichon frise', 'Bichon frisé'), ('Boiadeiro australiano', 'Boiadeiro australiano'), ('Border collie', 'Border collie'), ('Borzoi', 'Borzoi'), ('Boston terrier', 'Boston terrier'), ('Boxer', 'Boxer'), ('Buldogue frances', 'Buldogue francês'), ('Bull terrier', 'Bull terrier'), ('Cane corso', 'Cane corso'), ('Cavalier king charles spaniel', 'Cavalier king charles spaniel'), ('Chihuahua', 'Chihuahua'), ('Chow chow', 'Chow chow'), ('Cocker spaniel ingles', 'Cocker spaniel inglês'), ('Corgi', 'Corgi'), ('Dachshund', 'Dachshund'), ('Dalmata', 'Dálmata'), ('Doberman', 'Doberman'), ('Dogo argentino', 'Dogo argentino'), ('Dogue alemao', 'Dogue alemao'), ('Dogue de Bordeaux', 'Dogue de Bordeaux'), ('Fila brasileiro', 'Fila brasileiro'), ('Fox paulistinha', 'Fox paulistinha'), ('Galguinho italiano', 'Galguinho italiano'), ('Golden retriever', 'Golden retriever'), ('Greyhound ou Galgo ingles', 'Greyhound ou Galgo inglês'), ('Husky siberiano', 'Husky siberiano'), ('Jack russel terrier', 'Jack russel terrier'), ('Labradoodle', 'Labradoodle'), ('Labrador retriever', 'Labrador retriever'), ('Lhasa apso', 'Lhasa apso'), ('Lulu da Pomerania', 'Lulu da Pomerânia'), ('Malamute do alasca', 'Malamute do alasca'), ('Maltês ou Bichon Maltes', 'Maltês ou Bichon Maltês'), ('Mastiff ingles', 'Mastiff inglês'), ('Mastim Napolitano', 'Mastim Napolitano'), ('Mastim tibetano', 'Mastim tibetano'), ('Papillon', 'Papillon'), ('Pastor alemao', 'Pastor alemão'), ('Pastor alemao', 'Pastor australiano'), ('Pastor Belga', 'Pastor Belga'), ('Pastor de Shetland', 'Pastor de Shetland'), ('Pastor do Caucaso', 'Pastor do Cáucaso'), ('Pastor Maremano Abruzes', 'Pastor Maremano Abruzes'), ('Pastor Suiço', 'Pastor Suiço'), ('Pequines', 'Pequinês'), ('Pinscher miniatura', 'Pinscher miniatura'), ('Pit bull', 'Pit bull'), ('Pointer Ingles', 'Pointer Inglês'), ('Poodle', 'Poodle'), ('Poodle Toy', 'Poodle Toy'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Rough Collie', 'Rough Collie'), ('Samoieda', 'Samoieda'), ('Sao bernardo', 'São bernardo'), ('Schnauzer', 'Schnauzer'), ('Setter Irlandes', 'Setter Irlandês'), ('Shar-pei', 'Shar-pei'), ('Shiba', 'Shiba'), ('Shih tzu', 'Shih tzu'), ('Spitz Japones', 'Spitz Japonês'), ('Staffordshire bull terrier', 'Staffordshire bull terrier'), ('Terra nova', 'Terra nova'), ('Vira-lata', 'Vira-lata'), ('Weimaraner', 'Weimaraner'), ('West Highland White Terrier', 'West Highland White Terrier'), ('Whippet', 'Whippet'), ('Yorkshire Terrier', 'Yorkshire Terrier')], db_column='BREED', max_length=30)),
                ('size', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Médio'), ('Grande', 'Grande')], db_column='SIZE', max_length=7)),
                ('color', models.CharField(db_column='COLOR', max_length=20)),
                ('observation', models.TextField(blank=True, db_column='OBSERVATION')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
                'db_table': 'ANIMAL',
            },
        ),
    ]
