# Generated by Django 4.0.6 on 2022-08-08 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_column='EXTERNAL_ID', default=uuid.uuid4, editable=False, unique=True)),
                ('street', models.CharField(db_column='STREET', max_length=100)),
                ('neighborhood', models.CharField(db_column='NEIGHBORHOOD', max_length=100)),
                ('city', models.CharField(db_column='CITY', max_length=50)),
                ('state', models.CharField(choices=[('SC', 'Santa Catarina'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], db_column='STATE', max_length=2)),
                ('zip_code', models.CharField(db_column='ZIP_CODE', max_length=9)),
                ('house_number', models.CharField(db_column='HOUSE_NUMBER', max_length=5)),
                ('customer', models.ForeignKey(db_column='CUSTOMER', on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'ADDRESS',
            },
        ),
    ]
