# Generated by Django 4.0.6 on 2022-09-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='state',
        ),
    ]
