# Generated by Django 4.0.6 on 2022-08-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='customer',
            field=models.ForeignKey(db_column='CUSTOMER', on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel'),
        ),
    ]
