# Generated by Django 4.0.6 on 2022-09-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_addressmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='state',
        ),
    ]
